version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinelands-wildfire-app
    env_file:
      - .env.local
    environment:
      - IN_DOCKER=1
    ports:
      - "3000:3000"
    volumes:
      # bind your source for hot-reload
      - .:/app
      # but keep the node_modules from the image
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    container_name: wildfire-backend
    working_dir: /app
    env_file:
      - .env.local
    environment:
      - IN_DOCKER=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /Users/jimmullen/Downloads/pinelands:/app/pinelands:ro
      - /Users/jimmullen/CascadeProjects/pinelands-wildfire-app/National_Interagency_Fire_Occurrence_Sixth_Edition_1992-2020_(Feature_Layer).csv:/app/data/raw/fire_occurrence.csv:ro
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: wildfire-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wildfire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  node_modules:
  pgadmin-data:
