version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinelands-wildfire-app
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      # bind your source for hot-reload
      - .:/app
      # but keep the node_modules from the image
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    container_name: wildfire-backend
    working_dir: /app
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: wildfire-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wildfire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
