[build]
command = "pip install -r requirements.txt && python -m uvicorn app.main:app --host 0.0.0.0 --port 8080"
publish = "app/static"
functions = "api"

[build.environment]
PYTHON_VERSION = "3.11"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
